class GitWorkspaceError(Exception): ...


class GitCloneError(GitWorkspaceError): ...


class GitInitError(GitWorkspaceError): ...


class InvalidWorkspaceError(GitWorkspaceError): ...


class UnableToResolveWorkspaceError(GitWorkspaceError): ...


class UnableToResolveBranchError(GitWorkspaceError): ...


class WorkspaceCreationError(GitWorkspaceError): ...


class InvalidInputError(GitWorkspaceError): ...


class GitFetchError(GitWorkspaceError): ...


class WorktreeCreationError(GitWorkspaceError): ...


class WorktreeNotFoundError(GitWorkspaceError): ...


class WorktreeDirtyError(GitWorkspaceError): ...


class WorktreeRemovalError(GitWorkspaceError): ...


class WorkspaceLinkError(GitWorkspaceError): ...


class HookExecutionError(GitWorkspaceError): ...


class WorktreeListingError(GitWorkspaceError): ...


class WorktreeResolutionError(GitWorkspaceError): ...
