class GitWorkspaceError(Exception): ...


class GitCloneError(GitWorkspaceError): ...


class InvalidWorkspaceRootError(GitWorkspaceError): ...


class UnableToResolveWorkspaceRootError(GitWorkspaceError): ...


class WorkspaceCreationError(GitWorkspaceError): ...
