class GitWorkspaceError(Exception): ...


class GitCloneError(GitWorkspaceError): ...


class GitInitError(GitWorkspaceError): ...


class InvalidWorkspaceRootError(GitWorkspaceError): ...


class UnableToResolveWorkspaceRootError(GitWorkspaceError): ...


class WorkspaceCreationError(GitWorkspaceError): ...


class InvalidInputError(GitWorkspaceError): ...


class GitFetchError(GitWorkspaceError): ...


class WorktreeCreationError(GitWorkspaceError): ...
